In [1]:
import numpy as np

In [2]:
l=[1,2,3,4]

In [3]:
arr =np.array(l)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.asarray(l)

array([1, 2, 3, 4])

In [8]:
a=[2,3,4]

In [9]:
np.asanyarray(a)

array([2, 3, 4])

In [10]:
b= np.matrix(l)

In [11]:
b

matrix([[1, 2, 3, 4]])

In [12]:
type(b)

numpy.matrix

In [13]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [14]:
# swallow copy 
c=a

In [15]:
c

[2, 3, 4]

In [16]:
c[0]=100

In [17]:
c

[100, 3, 4]

In [18]:
a

[100, 3, 4]

In [19]:
# deep copy 
d= np.copy(a)

In [20]:
d

array([100,   3,   4])

In [21]:
a[1]=400

In [22]:
a

[100, 400, 4]

In [24]:
c

[100, 400, 4]

In [25]:
d

array([100,   3,   4])

In [28]:
np.fromfunction(lambda i,j:i==j ,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [29]:
np.fromfunction(lambda i,j : i*j ,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [39]:
iterable=(i*i for i in range(5))

In [40]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [46]:
np.fromstring('5,7',sep=', ')

array([5., 7.])

In [47]:
np.fromstring('4545 343 5343 43434 ',sep=" ")

array([ 4545.,   343.,  5343., 43434.])

In [48]:
#Numpy=data Types

In [49]:
l1=[1,2,3,4,56]

In [50]:
arr=np.array(l1)

In [51]:
arr

array([ 1,  2,  3,  4, 56])

In [52]:
arr.ndim

1

In [53]:
arr2=np.array([[1,2,3,4],[4,4,5,6]])

In [54]:
arr2

array([[1, 2, 3, 4],
       [4, 4, 5, 6]])

In [55]:
arr2.ndim

2

In [56]:
arr.size

5

In [57]:
arr2.size

8

In [58]:
arr.shape

(5,)

In [59]:
arr2.shape

(2, 4)

In [60]:
arr.dtype

dtype('int32')

In [61]:
arr2.dtype

dtype('int32')

In [63]:
arr3=np.array([(1,4,33.4,6),(5,64,3,2)])

In [64]:
arr3

array([[ 1. ,  4. , 33.4,  6. ],
       [ 5. , 64. ,  3. ,  2. ]])

In [65]:
arr3.dtype

dtype('float64')

In [68]:
list(range(5))

[0, 1, 2, 3, 4]

In [70]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [80]:
list(np.arange(2.3,9.0,.01))

[2.3,
 2.3099999999999996,
 2.3199999999999994,
 2.329999999999999,
 2.339999999999999,
 2.3499999999999988,
 2.3599999999999985,
 2.3699999999999983,
 2.379999999999998,
 2.389999999999998,
 2.3999999999999977,
 2.4099999999999975,
 2.4199999999999973,
 2.429999999999997,
 2.439999999999997,
 2.4499999999999966,
 2.4599999999999964,
 2.469999999999996,
 2.479999999999996,
 2.4899999999999958,
 2.4999999999999956,
 2.5099999999999953,
 2.519999999999995,
 2.529999999999995,
 2.5399999999999947,
 2.5499999999999945,
 2.5599999999999943,
 2.569999999999994,
 2.579999999999994,
 2.5899999999999936,
 2.5999999999999934,
 2.609999999999993,
 2.619999999999993,
 2.629999999999993,
 2.6399999999999926,
 2.6499999999999924,
 2.659999999999992,
 2.669999999999992,
 2.6799999999999917,
 2.6899999999999915,
 2.6999999999999913,
 2.709999999999991,
 2.719999999999991,
 2.7299999999999907,
 2.7399999999999904,
 2.7499999999999902,
 2.75999999999999,
 2.76999999999999,
 2.7799999999999896,
 2.7899999999999894,
 2.799999999999989,
 2.809999999999989,
 2.8199999999999887,
 2.8299999999999885,
 2.8399999999999883,
 2.849999999999988,
 2.859999999999988,
 2.8699999999999877,
 2.8799999999999875,
 2.8899999999999872,
 2.899999999999987,
 2.909999999999987,
 2.9199999999999866,
 2.9299999999999864,
 2.939999999999986,
 2.949999999999986,
 2.9599999999999858,
 2.9699999999999855,
 2.9799999999999853,
 2.989999999999985,
 2.999999999999985,
 3.0099999999999847,
 3.0199999999999845,
 3.0299999999999843,
 3.039999999999984,
 3.049999999999984,
 3.0599999999999836,
 3.0699999999999834,
 3.079999999999983,
 3.089999999999983,
 3.0999999999999828,
 3.1099999999999826,
 3.1199999999999823,
 3.129999999999982,
 3.139999999999982,
 3.1499999999999817,
 3.1599999999999815,
 3.1699999999999813,
 3.179999999999981,
 3.189999999999981,
 3.1999999999999806,
 3.2099999999999804,
 3.21999999999998,
 3.22999999999998,
 3.23999999999998,
 3.2499999999999796,
 3.2599999999999794,
 3.269999999999979,
 3.279999999999979,
 3.2899999999999787,
 3.2999999999999785,
 3.3099999999999783,
 3.319999999999978,
 3.329999999999978,
 3.3399999999999777,
 3.3499999999999774,
 3.3599999999999772,
 3.369999999999977,
 3.379999999999977,
 3.3899999999999766,
 3.3999999999999764,
 3.409999999999976,
 3.419999999999976,
 3.4299999999999757,
 3.4399999999999755,
 3.4499999999999753,
 3.459999999999975,
 3.469999999999975,
 3.4799999999999747,
 3.4899999999999745,
 3.4999999999999742,
 3.509999999999974,
 3.519999999999974,
 3.5299999999999736,
 3.5399999999999734,
 3.549999999999973,
 3.559999999999973,
 3.5699999999999728,
 3.5799999999999725,
 3.5899999999999723,
 3.599999999999972,
 3.609999999999972,
 3.6199999999999717,
 3.6299999999999715,
 3.6399999999999713,
 3.649999999999971,
 3.659999999999971,
 3.6699999999999706,
 3.6799999999999704,
 3.68999999999997,
 3.69999999999997,
 3.7099999999999698,
 3.7199999999999696,
 3.7299999999999693,
 3.739999999999969,
 3.749999999999969,
 3.7599999999999687,
 3.7699999999999685,
 3.7799999999999683,
 3.789999999999968,
 3.799999999999968,
 3.8099999999999676,
 3.8199999999999674,
 3.829999999999967,
 3.839999999999967,
 3.849999999999967,
 3.8599999999999666,
 3.8699999999999664,
 3.879999999999966,
 3.889999999999966,
 3.8999999999999657,
 3.9099999999999655,
 3.9199999999999653,
 3.929999999999965,
 3.939999999999965,
 3.9499999999999647,
 3.9599999999999644,
 3.9699999999999642,
 3.979999999999964,
 3.989999999999964,
 3.9999999999999636,
 4.009999999999963,
 4.019999999999963,
 4.029999999999963,
 4.039999999999963,
 4.0499999999999625,
 4.059999999999962,
 4.069999999999962,
 4.079999999999962,
 4.089999999999962,
 4.0999999999999615,
 4.109999999999961,
 4.119999999999961,
 4.129999999999961,
 4.139999999999961,
 4.14999999999996,
 4.15999999999996,
 4.16999999999996,
 4.17999999999996,
 4.1899999999999595,
 4.199999999999959,
 4.209999999999959,
 4.219999999999959,
 4.229999999999959,
 4.2399999999999585,
 4.249999999999958,
 4.259999999999958,
 4.269999999999958,
 4.279999999999958,
 4.289999999999957,
 4.299999999999957,
 4.309999999999957,
 4.319999999999957,
 4.3299999999999566,
 4.339999999999956,
 4.349999999999956,
 4.359999999999956,
 4.369999999999956,
 4.3799999999999555,
 4.389999999999955,
 4.399999999999955,
 4.409999999999955,
 4.419999999999955,
 4.429999999999954,
 4.439999999999954,
 4.449999999999954,
 4.459999999999954,
 4.469999999999954,
 4.479999999999953,
 4.489999999999953,
 4.499999999999953,
 4.509999999999953,
 4.5199999999999525,
 4.529999999999952,
 4.539999999999952,
 4.549999999999952,
 4.559999999999952,
 4.569999999999951,
 4.579999999999951,
 4.589999999999951,
 4.599999999999951,
 4.609999999999951,
 4.61999999999995,
 4.62999999999995,
 4.63999999999995,
 4.64999999999995,
 4.6599999999999495,
 4.669999999999949,
 4.679999999999949,
 4.689999999999949,
 4.699999999999949,
 4.7099999999999485,
 4.719999999999948,
 4.729999999999948,
 4.739999999999948,
 4.749999999999948,
 4.759999999999947,
 4.769999999999947,
 4.779999999999947,
 4.789999999999947,
 4.7999999999999465,
 4.809999999999946,
 4.819999999999946,
 4.829999999999946,
 4.839999999999946,
 4.8499999999999455,
 4.859999999999945,
 4.869999999999945,
 4.879999999999945,
 4.889999999999945,
 4.899999999999944,
 4.909999999999944,
 4.919999999999944,
 4.929999999999944,
 4.9399999999999435,
 4.949999999999943,
 4.959999999999943,
 4.969999999999943,
 4.979999999999943,
 4.9899999999999425,
 4.999999999999942,
 5.009999999999942,
 5.019999999999942,
 5.029999999999942,
 5.039999999999941,
 5.049999999999941,
 5.059999999999941,
 5.069999999999941,
 5.079999999999941,
 5.08999999999994,
 5.09999999999994,
 5.10999999999994,
 5.11999999999994,
 5.1299999999999395,
 5.139999999999939,
 5.149999999999939,
 5.159999999999939,
 5.169999999999939,
 5.179999999999938,
 5.189999999999938,
 5.199999999999938,
 5.209999999999938,
 5.219999999999938,
 5.229999999999937,
 5.239999999999937,
 5.249999999999937,
 5.259999999999937,
 5.2699999999999365,
 5.279999999999936,
 5.289999999999936,
 5.299999999999936,
 5.309999999999936,
 5.3199999999999354,
 5.329999999999935,
 5.339999999999935,
 5.349999999999935,
 5.359999999999935,
 5.369999999999934,
 5.379999999999934,
 5.389999999999934,
 5.399999999999934,
 5.4099999999999335,
 5.419999999999933,
 5.429999999999933,
 5.439999999999933,
 5.449999999999933,
 5.4599999999999325,
 5.469999999999932,
 5.479999999999932,
 5.489999999999932,
 5.499999999999932,
 5.509999999999931,
 5.519999999999931,
 5.529999999999931,
 5.539999999999931,
 5.5499999999999305,
 5.55999999999993,
 5.56999999999993,
 5.57999999999993,
 5.58999999999993,
 5.5999999999999295,
 5.609999999999929,
 5.619999999999929,
 5.629999999999929,
 5.639999999999929,
 5.649999999999928,
 5.659999999999928,
 5.669999999999928,
 5.679999999999928,
 5.689999999999928,
 5.699999999999927,
 5.709999999999927,
 5.719999999999927,
 5.729999999999927,
 5.7399999999999265,
 5.749999999999926,
 5.759999999999926,
 5.769999999999926,
 5.779999999999926,
 5.789999999999925,
 5.799999999999925,
 5.809999999999925,
 5.819999999999925,
 5.829999999999925,
 5.839999999999924,
 5.849999999999924,
 5.859999999999924,
 5.869999999999924,
 5.8799999999999235,
 5.889999999999923,
 5.899999999999923,
 5.909999999999923,
 5.919999999999923,
 5.9299999999999224,
 5.939999999999922,
 5.949999999999922,
 5.959999999999922,
 5.969999999999922,
 5.979999999999921,
 5.989999999999921,
 5.999999999999921,
 6.009999999999921,
 6.0199999999999205,
 6.02999999999992,
 6.03999999999992,
 6.04999999999992,
 6.05999999999992,
 6.0699999999999195,
 6.079999999999919,
 6.089999999999919,
 6.099999999999919,
 6.109999999999919,
 6.119999999999918,
 6.129999999999918,
 6.139999999999918,
 6.149999999999918,
 6.1599999999999175,
 6.169999999999917,
 6.179999999999917,
 6.189999999999917,
 6.199999999999917,
 6.2099999999999165,
 6.219999999999916,
 6.229999999999916,
 6.239999999999916,
 6.249999999999916,
 6.259999999999915,
 6.269999999999915,
 6.279999999999915,
 6.289999999999915,
 6.299999999999915,
 6.309999999999914,
 6.319999999999914,
 6.329999999999914,
 6.339999999999914,
 6.3499999999999135,
 6.359999999999913,
 6.369999999999913,
 6.379999999999913,
 6.389999999999913,
 6.399999999999912,
 6.409999999999912,
 6.419999999999912,
 6.429999999999912,
 6.439999999999912,
 6.449999999999911,
 6.459999999999911,
 6.469999999999911,
 6.479999999999911,
 6.4899999999999105,
 6.49999999999991,
 6.50999999999991,
 6.51999999999991,
 6.52999999999991,
 6.539999999999909,
 6.549999999999909,
 6.559999999999909,
 6.569999999999909,
 6.579999999999909,
 6.589999999999908,
 6.599999999999908,
 6.609999999999908,
 6.619999999999908,
 6.6299999999999075,
 6.639999999999907,
 6.649999999999907,
 6.659999999999907,
 6.669999999999907,
 6.6799999999999065,
 6.689999999999906,
 6.699999999999906,
 6.709999999999906,
 6.719999999999906,
 6.729999999999905,
 6.739999999999905,
 6.749999999999905,
 6.759999999999905,
 6.7699999999999045,
 6.779999999999904,
 6.789999999999904,
 6.799999999999904,
 6.809999999999904,
 6.8199999999999035,
 6.829999999999903,
 6.839999999999903,
 6.849999999999903,
 6.859999999999903,
 6.869999999999902,
 6.879999999999902,
 6.889999999999902,
 6.899999999999902,
 6.9099999999999016,
 6.919999999999901,
 6.929999999999901,
 6.939999999999901,
 6.949999999999901,
 6.9599999999999005,
 6.9699999999999,
 6.9799999999999,
 6.9899999999999,
 6.9999999999999,
 7.009999999999899,
 7.019999999999899,
 7.029999999999899,
 7.039999999999899,
 7.049999999999899,
 7.059999999999898,
 7.069999999999898,
 7.079999999999898,
 7.089999999999898,
 7.0999999999998975,
 7.109999999999897,
 7.119999999999897,
 7.129999999999897,
 7.139999999999897,
 7.149999999999896,
 7.159999999999896,
 7.169999999999896,
 7.179999999999896,
 7.189999999999896,
 7.199999999999895,
 7.209999999999895,
 7.219999999999895,
 7.229999999999895,
 7.2399999999998945,
 7.249999999999894,
 7.259999999999894,
 7.269999999999894,
 7.279999999999894,
 7.2899999999998935,
 7.299999999999893,
 7.309999999999893,
 7.319999999999893,
 7.329999999999893,
 7.339999999999892,
 7.349999999999892,
 7.359999999999892,
 7.369999999999892,
 7.3799999999998915,
 7.389999999999891,
 7.399999999999891,
 7.409999999999891,
 7.419999999999891,
 7.4299999999998905,
 7.43999999999989,
 7.44999999999989,
 7.45999999999989,
 7.46999999999989,
 7.479999999999889,
 7.489999999999889,
 7.499999999999889,
 7.509999999999889,
 7.5199999999998886,
 7.529999999999888,
 7.539999999999888,
 7.549999999999888,
 7.559999999999888,
 7.5699999999998875,
 7.579999999999887,
 7.589999999999887,
 7.599999999999887,
 7.609999999999887,
 7.619999999999886,
 7.629999999999886,
 7.639999999999886,
 7.649999999999886,
 7.659999999999886,
 7.669999999999885,
 7.679999999999885,
 7.689999999999885,
 7.699999999999885,
 7.7099999999998845,
 7.719999999999884,
 7.729999999999884,
 7.739999999999884,
 7.749999999999884,
 7.759999999999883,
 7.769999999999883,
 7.779999999999883,
 7.789999999999883,
 7.799999999999883,
 7.809999999999882,
 7.819999999999882,
 7.829999999999882,
 7.839999999999882,
 7.8499999999998815,
 7.859999999999881,
 7.869999999999881,
 7.879999999999881,
 7.889999999999881,
 7.8999999999998805,
 7.90999999999988,
 7.91999999999988,
 7.92999999999988,
 7.93999999999988,
 7.949999999999879,
 7.959999999999879,
 7.969999999999879,
 7.979999999999879,
 7.9899999999998785,
 7.999999999999878,
 8.009999999999877,
 8.019999999999879,
 8.029999999999877,
 8.039999999999878,
 8.049999999999876,
 8.059999999999878,
 8.069999999999876,
 8.079999999999878,
 8.089999999999876,
 8.099999999999877,
 8.109999999999875,
 8.119999999999877,
 8.129999999999875,
 8.139999999999876,
 8.149999999999874,
 8.159999999999876,
 8.169999999999874,
 8.179999999999875,
 8.189999999999873,
 8.199999999999875,
 8.209999999999873,
 8.219999999999875,
 8.229999999999873,
 8.239999999999874,
 8.249999999999872,
 8.259999999999874,
 8.269999999999872,
 8.279999999999873,
 8.289999999999871,
 8.299999999999873,
 8.30999999999987,
 8.319999999999872,
 8.32999999999987,
 8.339999999999872,
 8.34999999999987,
 8.359999999999872,
 8.36999999999987,
 8.379999999999871,
 8.38999999999987,
 8.39999999999987,
 8.409999999999869,
 8.41999999999987,
 8.429999999999868,
 8.43999999999987,
 8.449999999999868,
 8.45999999999987,
 8.469999999999867,
 8.479999999999869,
 8.489999999999867,
 8.499999999999869,
 8.509999999999867,
 8.519999999999868,
 8.529999999999866,
 8.539999999999868,
 8.549999999999866,
 8.559999999999867,
 8.569999999999865,
 8.579999999999867,
 8.589999999999865,
 8.599999999999866,
 8.609999999999864,
 8.619999999999866,
 8.629999999999864,
 8.639999999999866,
 8.649999999999864,
 8.659999999999865,
 8.669999999999863,
 8.679999999999865,
 8.689999999999863,
 8.699999999999864,
 8.709999999999862,
 8.719999999999864,
 8.729999999999862,
 8.739999999999863,
 8.749999999999861,
 8.759999999999863,
 8.769999999999861,
 8.779999999999863,
 8.78999999999986,
 8.799999999999862,
 8.80999999999986,
 8.819999999999862,
 8.82999999999986,
 8.839999999999861,
 8.84999999999986,
 8.85999999999986,
 8.869999999999859,
 8.87999999999986,
 8.889999999999858,
 8.89999999999986,
 8.909999999999858,
 8.91999999999986,
 8.929999999999858,
 8.93999999999986,
 8.949999999999857,
 8.959999999999859,
 8.969999999999857,
 8.979999999999858,
 8.989999999999856]

In [82]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [85]:
np.ones((8,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [87]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [90]:
arr5=np.ones((2,3,2))

In [91]:
arr5

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [92]:
arr5*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [96]:
np.empty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [97]:
np.eye(16)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [99]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [100]:
np.logspace(2,5,200)

array([   100.        ,    103.53218433,    107.18913192,    110.97524964,
          114.89510002,    118.95340674,    123.15506033,    127.50512407,
          132.00884008,    136.67163565,    141.49912974,    146.49713983,
          151.67168885,    157.02901247,    162.57556664,    168.31803533,
          174.2633386 ,    180.41864094,    186.7913599 ,    193.38917505,
          200.22003718,    207.29217796,    214.61411979,    222.19468609,
          230.04301198,    238.1685552 ,    246.58110758,    255.29080682,
          264.3081487 ,    273.64399971,    283.30961018,    293.31662784,
          303.6771118 ,    314.40354716,    325.50885998,    337.00643293,
          348.91012134,    361.23426997,    373.99373025,    387.20387818,
          400.88063289,    415.04047579,    429.70047043,    444.87828311,
          460.59220411,    476.86116977,    493.70478528,    511.14334834,
          529.1978736 ,    547.89011796,    567.24260685,    587.27866132,
          608.02242616,    629.49889902,    651.73396049,    674.75440531,
          698.58797468,    723.26338965,    748.81038576,    775.25974886,
          802.64335223,    830.99419494,    860.34644167,    890.73546386,
          922.19788233,    954.77161142,    988.49590466,   1023.41140211,
         1059.56017928,   1096.98579789,   1135.73335834,   1175.84955405,
         1217.38272774,   1260.38292968,   1304.90197801,   1350.9935212 ,
         1398.71310265,   1448.11822767,   1499.26843279,   1552.22535743,
         1607.05281826,   1663.81688608,   1722.5859654 ,   1783.43087693,
         1846.4249429 ,   1911.64407539,   1979.16686785,   2049.07468982,
         2121.45178491,   2196.38537242,   2273.96575236,   2354.28641432,
         2437.44415012,   2523.53917043,   2612.67522556,   2704.95973046,
         2800.50389418,   2899.42285388,   3001.83581358,   3107.86618778,
         3217.64175025,   3331.29478793,   3448.96226041,   3570.7859649 ,
         3696.9127072 ,   3827.49447852,   3962.6886387 ,   4102.65810583,
         4247.57155254,   4397.6036093 ,   4552.93507487,   4713.75313412,
         4880.25158365,   5052.63106534,   5231.09930806,   5415.87137808,
         5607.16993821,   5805.22551609,   6010.27678207,   6222.57083673,
         6442.36350872,   6669.91966303,   6905.51352016,   7149.4289866 ,
         7401.95999692,   7663.41086801,   7934.0966658 ,   8214.34358492,
         8504.4893418 ,   8804.88358164,   9115.88829975,   9437.87827778,
         9771.24153535,  10116.37979766,  10473.70897959,  10843.6596869 ,
        11226.67773511,  11623.2246868 ,  12033.77840778,  12458.83364295,
        12898.90261253,  13354.5156293 ,  13826.22173765,  14314.58937523,
        14820.20705799,  15343.6840893 ,  15885.65129428,  16446.76177995,
        17027.69172226,  17629.14118096,  18251.83494319,  18896.52339691,
        19563.98343517,  20255.01939231,  20970.46401323,  21711.17945695,
        22478.05833549,  23272.0247896 ,  24094.0356024 ,  24945.0813523 ,
        25826.18760683,  26738.4161584 ,  27682.86630392,  28660.67616948,
        29673.02408189,  30721.12998862,  31806.25692794,  32929.71255097,
        34092.85069747,  35297.07302731,  36543.83070957,  37834.62617132,
        39171.01490809,  40554.60735841,  41987.07084444,  43470.13158125,
        45005.576757  ,  46595.25668665,  48241.08704165,  49945.05115855,
        51709.20242897,  53535.66677411,  55426.64520663,  57384.41648302,
        59411.33984965,  61509.85788581,  63682.49944719,  65931.88271334,
        68260.71834272,  70671.81273927,  73168.07143427,  75752.50258772,
        78428.22061338,  81198.44993184,  84066.52885618,  87035.91361485,
        90110.18251665,  93293.04026285,  96588.32241159, 100000.        ])

In [102]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [106]:
arr6=np.random.randn(3,4)

In [107]:
import pandas as pd

In [108]:
pd.DataFrame(arr6)

          0         1         2         3
0  0.359834 -0.613827 -1.127225  0.292258
1  0.864378  1.129332  1.482280  0.677651
2 -0.337016  0.936707  0.214799  0.484269

In [109]:
np.random.rand(3,7)

array([[0.14869616, 0.15210125, 0.31839576, 0.94082133, 0.13418727,
        0.10530704, 0.79074017],
       [0.21004304, 0.64498346, 0.14344418, 0.78147815, 0.64022769,
        0.55982352, 0.15017312],
       [0.3188358 , 0.52525247, 0.79734593, 0.96451646, 0.94634281,
        0.07281107, 0.42889978]])

In [110]:
pd.DataFrame(np.random.rand(4,5))

          0         1         2         3         4
0  0.179289  0.140957  0.430835  0.245339  0.649212
1  0.018104  0.629063  0.099326  0.458775  0.673440
2  0.946026  0.137488  0.053704  0.326373  0.058505
3  0.446799  0.178261  0.453272  0.295293  0.846561

In [111]:
np.random.randint(2,220,(5,5))

array([[166, 154,  44,  23,   9],
       [ 67, 150, 119,  44, 201],
       [ 27, 155,  69, 215, 128],
       [ 41, 197, 137,  60,  49],
       [120, 139,  33,  76, 146]])

In [112]:
pd.DataFrame(np.random.randint(2,220,(300,400))).to_csv("test.csv")

In [113]:
arr7=np.random.rand(3,4)

In [114]:
arr7

array([[0.97643132, 0.37129977, 0.48582942, 0.19083978],
       [0.70624454, 0.69207355, 0.01576252, 0.00551988],
       [0.0816228 , 0.89158668, 0.72745765, 0.29228988]])

In [117]:
arr8=arr7.reshape(6,-1)

In [118]:
arr8

array([[0.97643132, 0.37129977],
       [0.48582942, 0.19083978],
       [0.70624454, 0.69207355],
       [0.01576252, 0.00551988],
       [0.0816228 , 0.89158668],
       [0.72745765, 0.29228988]])

In [120]:
arr8[1][1]

0.19083978242970778

In [124]:
arr8[2:5,0]

array([0.70624454, 0.01576252, 0.0816228 ])

In [125]:
arr10=np.random.randint(1,100,(5,5))

In [126]:
arr10

array([[88, 38, 49, 17,  8],
       [48, 15, 95, 93, 65],
       [75, 65, 51, 30, 76],
       [52, 29, 36, 89,  6],
       [ 5, 15, 77, 21, 91]])

In [129]:
arr10[arr10>5]

array([88, 38, 49, 17,  8, 48, 15, 95, 93, 65, 75, 65, 51, 30, 76, 52, 29,
       36, 89,  6, 15, 77, 21, 91])

In [130]:
arr10

array([[88, 38, 49, 17,  8],
       [48, 15, 95, 93, 65],
       [75, 65, 51, 30, 76],
       [52, 29, 36, 89,  6],
       [ 5, 15, 77, 21, 91]])

In [135]:
arr10[1:3,[1,3]]

array([[15, 93],
       [65, 30]])

In [136]:
arr11=np.random.randint(1,3,(3,3))

In [142]:
arr12=np.random.randint(4,8,(3,3))

In [138]:
arr11

array([[1, 2, 2],
       [2, 2, 2],
       [1, 1, 2]])

In [143]:
arr12

array([[5, 5, 4],
       [4, 5, 6],
       [6, 6, 5]])

In [144]:
arr11+arr12

array([[6, 7, 6],
       [6, 7, 8],
       [7, 7, 7]])

In [145]:
arr11*arr12

array([[ 5, 10,  8],
       [ 8, 10, 12],
       [ 6,  6, 10]])

In [146]:
# Matrix Multiplication

arr11@arr12

array([[25, 27, 26],
       [30, 32, 30],
       [21, 22, 20]])

In [147]:
arr11/0

C:\Users\RomulusDome\AppData\Local\Temp\ipykernel_11772\3085431103.py:1: RuntimeWarning: divide by zero encountered in divide
  arr11/0

array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [148]:
arr11**2

array([[1, 4, 4],
       [4, 4, 4],
       [1, 1, 4]])

In [149]:
# Numpy Broadcasting

In [150]:
arr13=np.zeros((4,4))

In [151]:
arr13

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [152]:
row =np.array([1,2,3,4])

In [153]:
row

array([1, 2, 3, 4])

In [154]:
arr13+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [155]:
row.T

array([1, 2, 3, 4])

In [156]:
col=np.array([[1,2,34,3]])

In [157]:
col

array([[ 1,  2, 34,  3]])

In [158]:
col.T

array([[ 1],
       [ 2],
       [34],
       [ 3]])

In [159]:
col.T + arr13

array([[ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [34., 34., 34., 34.],
       [ 3.,  3.,  3.,  3.]])

In [160]:
np.exp(arr13)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [162]:
np.log2(arr13)

C:\Users\RomulusDome\AppData\Local\Temp\ipykernel_11772\3488241091.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr13)

array([[-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])

In [164]:
arr14=np.random.randint(1,3,(3,4))

In [165]:
arr14

array([[2, 1, 1, 1],
       [1, 1, 2, 1],
       [1, 1, 1, 2]])

In [166]:
np.sqrt(arr14)

array([[1.41421356, 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.        , 1.41421356]])

In [167]:
np.exp2(arr14)

array([[4., 2., 2., 2.],
       [2., 2., 4., 2.],
       [2., 2., 2., 4.]])

In [168]:
np.log2(arr14)

array([[1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [170]:
np.log(arr14)

array([[0.69314718, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.69314718, 0.        ],
       [0.        , 0.        , 0.        , 0.69314718]])